/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Juan Suaza
 */
public class frameAuxiliar extends javax.swing.JFrame {

    /**
     * Creates new form frameAuxiliar
     */
    CardLayout clAuxiliar;
    
    public frameAuxiliar() {
        initComponents();
        
        //Adicion de componentes al cardLayout
        panelContenedor.setLayout(new CardLayout());
        
        panelContenedor.add(panelInicialSlogan, "Inicio");
        panelContenedor.add(ventaTarjetasPanel, "Venta");
        panelContenedor.add(personalizacionPanel, "Personalizacion");
        panelContenedor.add(recargaSaldoPanel, "Recarga");
        panelContenedor.add(consultaSaldoPanel, "Consulta");
        panelContenedor.add(hacerSolicitudPanel, "Solicitud");
        
        clAuxiliar = (CardLayout)panelContenedor.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicialSlogan = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        ventaTarjetasPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigoTarjetaVenta = new javax.swing.JTextField();
        numeroPasajesVenta = new javax.swing.JSpinner();
        aceptarVenderTarjeta = new javax.swing.JButton();
        personalizacionPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        codigoPersonalizacion = new javax.swing.JTextField();
        nombrePersonalizacion = new javax.swing.JTextField();
        cedulaPersonalizacion = new javax.swing.JTextField();
        estacionesPersonalizacion = new javax.swing.JComboBox();
        aceptarPersonalizacion = new javax.swing.JButton();
        buscarCodigoPersonalizacion = new javax.swing.JLabel();
        recargaSaldoPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        codigoRecargar = new javax.swing.JTextField();
        pasajesActualesRecargar = new javax.swing.JLabel();
        pasajesNuevosRecargar = new javax.swing.JSpinner();
        aceptarRecargar = new javax.swing.JButton();
        buscarCodigoRecarga = new javax.swing.JLabel();
        consultaSaldoPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        codigoConsultar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pasajesActualesConsultar = new javax.swing.JLabel();
        buscarCodigoConsultar = new javax.swing.JLabel();
        aceptarConsultaSaldo = new javax.swing.JButton();
        hacerSolicitudPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tiqueteSolicitud = new javax.swing.JTextField();
        cedulaPasajeroSolicitud = new javax.swing.JTextField();
        cedulaEmpleadoSolicitud = new javax.swing.JTextField();
        estacionesSolicitud = new javax.swing.JComboBox();
        motivosSolicitud = new javax.swing.JComboBox();
        scrollPaneDescripcion = new javax.swing.JScrollPane();
        descripcionSolicitud = new javax.swing.JTextArea();
        aceptarSolicitud = new javax.swing.JButton();
        buscarCodigoConsultar1 = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ventaTarjetasBoton = new javax.swing.JButton();
        personalizacionBoton = new javax.swing.JButton();
        recargaSaldoBoton = new javax.swing.JButton();
        consultaSaldoBoton = new javax.swing.JButton();
        haacerSolicitudBoton = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        panelInicialSlogan.setBackground(new java.awt.Color(255, 255, 255));

        slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/slogan.png"))); // NOI18N

        javax.swing.GroupLayout panelInicialSloganLayout = new javax.swing.GroupLayout(panelInicialSlogan);
        panelInicialSlogan.setLayout(panelInicialSloganLayout);
        panelInicialSloganLayout.setHorizontalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialSloganLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(slogan)
                .addGap(39, 39, 39))
        );
        panelInicialSloganLayout.setVerticalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(slogan)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        ventaTarjetasPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Código de la tarjeta:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pasajes:");

        codigoTarjetaVenta.setEditable(false);
        codigoTarjetaVenta.setBackground(new java.awt.Color(255, 255, 255));

        aceptarVenderTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarVenderTarjeta.setBorder(null);

        javax.swing.GroupLayout ventaTarjetasPanelLayout = new javax.swing.GroupLayout(ventaTarjetasPanel);
        ventaTarjetasPanel.setLayout(ventaTarjetasPanelLayout);
        ventaTarjetasPanelLayout.setHorizontalGroup(
            ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaTarjetasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoTarjetaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroPasajesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarVenderTarjeta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        ventaTarjetasPanelLayout.setVerticalGroup(
            ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaTarjetasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codigoTarjetaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventaTarjetasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numeroPasajesVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptarVenderTarjeta)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        personalizacionPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Código de la tarjeta:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nombre del pasajero:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cédula del pasajero:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Estación:");

        estacionesPersonalizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione una estación --" }));

        aceptarPersonalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarPersonalizacion.setBorder(null);

        buscarCodigoPersonalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N

        javax.swing.GroupLayout personalizacionPanelLayout = new javax.swing.GroupLayout(personalizacionPanel);
        personalizacionPanel.setLayout(personalizacionPanelLayout);
        personalizacionPanelLayout.setHorizontalGroup(
            personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalizacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptarPersonalizacion)
                    .addGroup(personalizacionPanelLayout.createSequentialGroup()
                        .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombrePersonalizacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaPersonalizacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estacionesPersonalizacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoPersonalizacion, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18)
                .addComponent(buscarCodigoPersonalizacion)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        personalizacionPanelLayout.setVerticalGroup(
            personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalizacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(codigoPersonalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarCodigoPersonalizacion))
                .addGap(18, 18, 18)
                .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombrePersonalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cedulaPersonalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalizacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(estacionesPersonalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(aceptarPersonalizacion)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        recargaSaldoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Código de la tarjeta:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Cantidad actual:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Recargar:");

        pasajesActualesRecargar.setText("0");

        aceptarRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarRecargar.setBorder(null);

        buscarCodigoRecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N

        javax.swing.GroupLayout recargaSaldoPanelLayout = new javax.swing.GroupLayout(recargaSaldoPanel);
        recargaSaldoPanel.setLayout(recargaSaldoPanelLayout);
        recargaSaldoPanelLayout.setHorizontalGroup(
            recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recargaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptarRecargar)
                    .addGroup(recargaSaldoPanelLayout.createSequentialGroup()
                        .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasajesActualesRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasajesNuevosRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(buscarCodigoRecarga)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        recargaSaldoPanelLayout.setVerticalGroup(
            recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recargaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(codigoRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarCodigoRecarga))
                .addGap(18, 18, 18)
                .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pasajesActualesRecargar))
                .addGap(18, 18, 18)
                .addGroup(recargaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pasajesNuevosRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptarRecargar)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        consultaSaldoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Código de la tarjeta:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Cantidad actual:");

        pasajesActualesConsultar.setText("0");

        buscarCodigoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N

        aceptarConsultaSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarConsultaSaldo.setBorder(null);

        javax.swing.GroupLayout consultaSaldoPanelLayout = new javax.swing.GroupLayout(consultaSaldoPanel);
        consultaSaldoPanel.setLayout(consultaSaldoPanelLayout);
        consultaSaldoPanelLayout.setHorizontalGroup(
            consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pasajesActualesConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                        .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptarConsultaSaldo)
                            .addComponent(codigoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buscarCodigoConsultar)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        consultaSaldoPanelLayout.setVerticalGroup(
            consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(codigoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCodigoConsultar))
                .addGap(18, 18, 18)
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pasajesActualesConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptarConsultaSaldo)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        hacerSolicitudPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Cédula del pasajero:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Cédula del auxiliar:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Número de tiquete:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Estación:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Motivo:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Descripción:");

        estacionesSolicitud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione una estación --" }));

        motivosSolicitud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione un motivo --", "Daños en la estación", "Daños en los buses", "Demora en las rutas", "Estación sin empleados", "No hay sistema", "Actitud del empleado" }));

        descripcionSolicitud.setColumns(20);
        descripcionSolicitud.setRows(5);
        scrollPaneDescripcion.setViewportView(descripcionSolicitud);

        aceptarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarSolicitud.setBorder(null);

        buscarCodigoConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N

        javax.swing.GroupLayout hacerSolicitudPanelLayout = new javax.swing.GroupLayout(hacerSolicitudPanel);
        hacerSolicitudPanel.setLayout(hacerSolicitudPanelLayout);
        hacerSolicitudPanelLayout.setHorizontalGroup(
            hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                        .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptarSolicitud)
                            .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(48, 48, 48)
                                .addComponent(scrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                        .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                                        .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hacerSolicitudPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)))
                                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(motivosSolicitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cedulaEmpleadoSolicitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estacionesSolicitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                                        .addComponent(cedulaPasajeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarCodigoConsultar1))
                                    .addComponent(tiqueteSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        hacerSolicitudPanelLayout.setVerticalGroup(
            hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tiqueteSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(cedulaPasajeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarCodigoConsultar1))
                .addGap(17, 17, 17)
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cedulaEmpleadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(estacionesSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(motivosSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(hacerSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(hacerSolicitudPanelLayout.createSequentialGroup()
                        .addComponent(scrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aceptarSolicitud)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banner.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/online-store-1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/id-card-5.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banker.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/dollar-symbol-2.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/customer-service.png"))); // NOI18N

        ventaTarjetasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/ventaTarjetas.png"))); // NOI18N
        ventaTarjetasBoton.setBorder(null);

        personalizacionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/personalizacion.png"))); // NOI18N
        personalizacionBoton.setBorder(null);

        recargaSaldoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/recargaSaldo.png"))); // NOI18N
        recargaSaldoBoton.setBorder(null);

        consultaSaldoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/consultarSaldo.png"))); // NOI18N
        consultaSaldoBoton.setBorder(null);

        haacerSolicitudBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/hacerSolicitud.png"))); // NOI18N
        haacerSolicitudBoton.setBorder(null);

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(haacerSolicitudBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(consultaSaldoBoton))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(recargaSaldoBoton))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ventaTarjetasBoton))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(personalizacionBoton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelFondoLayout.createSequentialGroup()
                                        .addComponent(ventaTarjetasBoton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(personalizacionBoton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(recargaSaldoBoton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(consultaSaldoBoton)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(banner)
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(haacerSolicitudBoton))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAuxiliar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarConsultaSaldo;
    private javax.swing.JButton aceptarPersonalizacion;
    private javax.swing.JButton aceptarRecargar;
    private javax.swing.JButton aceptarSolicitud;
    private javax.swing.JButton aceptarVenderTarjeta;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel buscarCodigoConsultar;
    private javax.swing.JLabel buscarCodigoConsultar1;
    private javax.swing.JLabel buscarCodigoPersonalizacion;
    private javax.swing.JLabel buscarCodigoRecarga;
    private javax.swing.JTextField cedulaEmpleadoSolicitud;
    private javax.swing.JTextField cedulaPasajeroSolicitud;
    private javax.swing.JTextField cedulaPersonalizacion;
    private javax.swing.JTextField codigoConsultar;
    private javax.swing.JTextField codigoPersonalizacion;
    private javax.swing.JTextField codigoRecargar;
    private javax.swing.JTextField codigoTarjetaVenta;
    private javax.swing.JButton consultaSaldoBoton;
    private javax.swing.JPanel consultaSaldoPanel;
    private javax.swing.JTextArea descripcionSolicitud;
    private javax.swing.JComboBox estacionesPersonalizacion;
    private javax.swing.JComboBox estacionesSolicitud;
    private javax.swing.JButton haacerSolicitudBoton;
    private javax.swing.JPanel hacerSolicitudPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox motivosSolicitud;
    private javax.swing.JTextField nombrePersonalizacion;
    private javax.swing.JSpinner numeroPasajesVenta;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInicialSlogan;
    private javax.swing.JLabel pasajesActualesConsultar;
    private javax.swing.JLabel pasajesActualesRecargar;
    private javax.swing.JSpinner pasajesNuevosRecargar;
    private javax.swing.JButton personalizacionBoton;
    private javax.swing.JPanel personalizacionPanel;
    private javax.swing.JButton recargaSaldoBoton;
    private javax.swing.JPanel recargaSaldoPanel;
    private javax.swing.JScrollPane scrollPaneDescripcion;
    private javax.swing.JLabel slogan;
    private javax.swing.JTextField tiqueteSolicitud;
    private javax.swing.JButton ventaTarjetasBoton;
    private javax.swing.JPanel ventaTarjetasPanel;
    // End of variables declaration//GEN-END:variables
}
