/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Juan Suaza
 */
public class frameDirectorOperativo extends javax.swing.JFrame {

    /**
     * Creates new form frameDirectorOperativo
     */
    public frameDirectorOperativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicialSlogan = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        frameOpciones = new javax.swing.JFrame();
        panelFondoOpciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        consultarSaldo = new javax.swing.JLabel();
        consultarRuta = new javax.swing.JLabel();
        abordarBus = new javax.swing.JLabel();
        consultarSolicitud = new javax.swing.JLabel();
        estacionesBoton = new javax.swing.JButton();
        rutasBoton = new javax.swing.JButton();
        busesBoton = new javax.swing.JButton();
        asignarTurnoBoton = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();

        panelInicialSlogan.setBackground(new java.awt.Color(255, 255, 255));

        slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/slogan.png"))); // NOI18N

        javax.swing.GroupLayout panelInicialSloganLayout = new javax.swing.GroupLayout(panelInicialSlogan);
        panelInicialSlogan.setLayout(panelInicialSloganLayout);
        panelInicialSloganLayout.setHorizontalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialSloganLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(slogan)
                .addGap(39, 39, 39))
        );
        panelInicialSloganLayout.setVerticalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(slogan)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        panelFondoOpciones.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/add-3.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/settings-4.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/close.png"))); // NOI18N

        javax.swing.GroupLayout panelFondoOpcionesLayout = new javax.swing.GroupLayout(panelFondoOpciones);
        panelFondoOpciones.setLayout(panelFondoOpcionesLayout);
        panelFondoOpcionesLayout.setHorizontalGroup(
            panelFondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoOpcionesLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        panelFondoOpcionesLayout.setVerticalGroup(
            panelFondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoOpcionesLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(panelFondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(381, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameOpcionesLayout = new javax.swing.GroupLayout(frameOpciones.getContentPane());
        frameOpciones.getContentPane().setLayout(frameOpcionesLayout);
        frameOpcionesLayout.setHorizontalGroup(
            frameOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOpcionesLayout.createSequentialGroup()
                .addComponent(panelFondoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameOpcionesLayout.setVerticalGroup(
            frameOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOpcionesLayout.createSequentialGroup()
                .addComponent(panelFondoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        consultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/street.png"))); // NOI18N

        consultarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/route.png"))); // NOI18N

        abordarBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/bus.png"))); // NOI18N

        consultarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/stopwatch-1.png"))); // NOI18N

        estacionesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/estaciones.png"))); // NOI18N
        estacionesBoton.setBorder(null);

        rutasBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/rutas.png"))); // NOI18N
        rutasBoton.setBorder(null);

        busesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/buses.png"))); // NOI18N
        busesBoton.setBorder(null);

        asignarTurnoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/asignarTurno.png"))); // NOI18N
        asignarTurnoBoton.setBorder(null);

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banner.png"))); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(consultarRuta)
                        .addGap(18, 18, 18)
                        .addComponent(rutasBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(consultarSaldo)
                        .addGap(18, 18, 18)
                        .addComponent(estacionesBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abordarBus)
                            .addComponent(consultarSolicitud))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busesBoton)
                            .addComponent(asignarTurnoBoton))))
                .addGap(26, 26, 26)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(17, 17, 17)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarSaldo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(estacionesBoton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarRuta)
                            .addComponent(rutasBoton))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(abordarBus)
                            .addComponent(busesBoton))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarSolicitud)
                            .addComponent(asignarTurnoBoton)))
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDirectorOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDirectorOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDirectorOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDirectorOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDirectorOperativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abordarBus;
    private javax.swing.JButton asignarTurnoBoton;
    private javax.swing.JLabel banner;
    private javax.swing.JButton busesBoton;
    private javax.swing.JLabel consultarRuta;
    private javax.swing.JLabel consultarSaldo;
    private javax.swing.JLabel consultarSolicitud;
    private javax.swing.JButton estacionesBoton;
    private javax.swing.JFrame frameOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoOpciones;
    private javax.swing.JPanel panelInicialSlogan;
    private javax.swing.JButton rutasBoton;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
