/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Reportes.Reporte;
import Usuarios.ControladorUsuario;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Suaza
 */
public class frameGerente extends javax.swing.JFrame {

    /**
     * Creates new form frameGerente
     */
    
    ControladorUsuario cUsuario;
    CardLayout cl;
    ButtonGroup reportes;
    public frameGerente() {
        initComponents();
        cUsuario = new ControladorUsuario();
        
        panelContenedor.setLayout(new CardLayout());
        panelContenedor.add(panelInicialSlogan, "Inicio");
        panelContenedor.add(panelSeleccionReporte, "Seleccionar reporte");
        panelContenedor.add(panelAgregarUsuario, "Agregar usuario");

        cl = (CardLayout)panelContenedor.getLayout();
        
        reportes = new ButtonGroup();
        reportes.add(pasajeroSistemaReporte);
        reportes.add(pasajerosMovilizadosReporte);
        reportes.add(ganaciaVentasReporte);
        reportes.add(listadoBusesReporte);
        reportes.add(listadoRutasReporte);
        reportes.add(listadoSolicitudesReporte);
        reportes.add(quejasReporte);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeleccionReporte = new javax.swing.JPanel();
        pasajeroSistemaReporte = new javax.swing.JRadioButton();
        pasajerosMovilizadosReporte = new javax.swing.JRadioButton();
        ganaciaVentasReporte = new javax.swing.JRadioButton();
        listadoSolicitudesReporte = new javax.swing.JRadioButton();
        listadoBusesReporte = new javax.swing.JRadioButton();
        listadoRutasReporte = new javax.swing.JRadioButton();
        quejasReporte = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox();
        mes = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        aceptarSeleccionReporte = new javax.swing.JButton();
        panelAgregarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cedulaCrearEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreCrearEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordCrearEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cargoCrearEmpleado = new javax.swing.JComboBox();
        aceptarCrearUsuario = new javax.swing.JButton();
        panelInicialSlogan = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reportesBoton = new javax.swing.JButton();
        empleadosBoton = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        panelSeleccionReporte.setBackground(new java.awt.Color(255, 255, 255));

        pasajeroSistemaReporte.setBackground(new java.awt.Color(255, 255, 255));
        pasajeroSistemaReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pasajeroSistemaReporte.setText("Pasajeros del sistema");

        pasajerosMovilizadosReporte.setBackground(new java.awt.Color(255, 255, 255));
        pasajerosMovilizadosReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pasajerosMovilizadosReporte.setText("Total de pasajeros movilizados");

        ganaciaVentasReporte.setBackground(new java.awt.Color(255, 255, 255));
        ganaciaVentasReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ganaciaVentasReporte.setText("Ganancia por venta de tarjetas");

        listadoSolicitudesReporte.setBackground(new java.awt.Color(255, 255, 255));
        listadoSolicitudesReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listadoSolicitudesReporte.setText("Listado de solicitudes");

        listadoBusesReporte.setBackground(new java.awt.Color(255, 255, 255));
        listadoBusesReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listadoBusesReporte.setText("Listado de buses");

        listadoRutasReporte.setBackground(new java.awt.Color(255, 255, 255));
        listadoRutasReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listadoRutasReporte.setText("Listado de rutas");

        quejasReporte.setBackground(new java.awt.Color(255, 255, 255));
        quejasReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quejasReporte.setText("Quejas más comunes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Día:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Mes:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Año:");

        dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "26", "27", "28", "29", "30", "31" }));

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2020" }));
        year.setSelectedIndex(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aceptarSeleccionReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarSeleccionReporte.setBorder(null);
        aceptarSeleccionReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarSeleccionReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionReporteLayout = new javax.swing.GroupLayout(panelSeleccionReporte);
        panelSeleccionReporte.setLayout(panelSeleccionReporteLayout);
        panelSeleccionReporteLayout.setHorizontalGroup(
            panelSeleccionReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeleccionReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptarSeleccionReporte)
                    .addGroup(panelSeleccionReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pasajeroSistemaReporte)
                        .addComponent(pasajerosMovilizadosReporte)
                        .addComponent(listadoSolicitudesReporte)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ganaciaVentasReporte)
                        .addComponent(listadoBusesReporte)
                        .addGroup(panelSeleccionReporteLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(panelSeleccionReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quejasReporte)
                                .addComponent(listadoRutasReporte)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelSeleccionReporteLayout.setVerticalGroup(
            panelSeleccionReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasajeroSistemaReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pasajerosMovilizadosReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ganaciaVentasReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listadoSolicitudesReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listadoBusesReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listadoRutasReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quejasReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarSeleccionReporte)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelAgregarUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cédula:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Contraseña:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cargo:");

        cargoCrearEmpleado.setMaximumRowCount(6);
        cargoCrearEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione un cargo --", "Conductor", "Director operativo", "Auxiliar de servicio al cliente", "Vendedor", "Director de estacion", " ", " ", " " }));

        aceptarCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarCrearUsuario.setBorder(null);
        aceptarCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarUsuarioLayout = new javax.swing.GroupLayout(panelAgregarUsuario);
        panelAgregarUsuario.setLayout(panelAgregarUsuarioLayout);
        panelAgregarUsuarioLayout.setHorizontalGroup(
            panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreCrearEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(cedulaCrearEmpleado)))
                    .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(aceptarCrearUsuario)
                        .addGroup(panelAgregarUsuarioLayout.createSequentialGroup()
                            .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(35, 35, 35)
                            .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cargoCrearEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordCrearEmpleado)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelAgregarUsuarioLayout.setVerticalGroup(
            panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarUsuarioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedulaCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cargoCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptarCrearUsuario)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        panelInicialSlogan.setBackground(new java.awt.Color(255, 255, 255));

        slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/slogan.png"))); // NOI18N

        javax.swing.GroupLayout panelInicialSloganLayout = new javax.swing.GroupLayout(panelInicialSlogan);
        panelInicialSlogan.setLayout(panelInicialSloganLayout);
        panelInicialSloganLayout.setHorizontalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(slogan)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelInicialSloganLayout.setVerticalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(slogan)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banner.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/bars-chart.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/id-card.png"))); // NOI18N

        reportesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/reportes.png"))); // NOI18N
        reportesBoton.setBorder(null);
        reportesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesBotonActionPerformed(evt);
            }
        });

        empleadosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/empleadosAgregar.png"))); // NOI18N
        empleadosBoton.setBorder(null);
        empleadosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosBotonActionPerformed(evt);
            }
        });

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(reportesBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(empleadosBoton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(reportesBoton)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(empleadosBoton))
                        .addGap(254, 254, 254))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(banner)
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarCrearUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = nombreCrearEmpleado.getText();
            int cedula = Integer.parseInt(cedulaCrearEmpleado.getText());
            String password = passwordCrearEmpleado.getText();
            String cargo = cargoCrearEmpleado.getSelectedItem().toString();
            if (!cargo.equals("-- Seleccione un cargo --")) {
                int id_cargo = cUsuario.obtenerCodigoCargo(cargo);
                String cedula_s = "" + cedula;
                int numFilas = cUsuario.agregarEmpleado(nombre, cedula_s, password, id_cargo);
                if (numFilas != -1 && numFilas != 0) {
                    JOptionPane.showMessageDialog(null, "Empleado registrado!");
                    nombreCrearEmpleado.setText("");
                    cedulaCrearEmpleado.setText("");
                    passwordCrearEmpleado.setText("");
                    cargoCrearEmpleado.setSelectedIndex(0);
                }else{
                    JOptionPane.showMessageDialog(null, "Empleado no registrado!");
                }
            }
        } catch (NumberFormatException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "El campo de cedula debe ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_aceptarCrearUsuarioActionPerformed

    private void empleadosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosBotonActionPerformed
        // TODO add your handling code here:
        cl.show(panelContenedor, "Agregar usuario");
        nombreCrearEmpleado.setText("");
        cedulaCrearEmpleado.setText("");
        passwordCrearEmpleado.setText("");
        cargoCrearEmpleado.setSelectedIndex(0);
    }//GEN-LAST:event_empleadosBotonActionPerformed

    private void reportesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesBotonActionPerformed
        // TODO add your handling code here:
        cl.show(panelContenedor, "Seleccionar reporte");
    }//GEN-LAST:event_reportesBotonActionPerformed

    private void aceptarSeleccionReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarSeleccionReporteActionPerformed
        // TODO add your handling code here:
        String dia_s = dia.getSelectedItem().toString();
        String mes_s = mes.getSelectedItem().toString();
        String year_s = year.getSelectedItem().toString();
        Reporte reporte  = new Reporte();
        if(pasajeroSistemaReporte.isSelected()){
            //reporte.crearReportePasajerosSistema();         
        }else if(pasajerosMovilizadosReporte.isSelected()){
            //reporte.crearReportePasajerosMovilizados();
        }else if(ganaciaVentasReporte.isSelected()){
            //reporte.crearReporteGanancias(dia_s, mes_s, year_s);    
        }else if(listadoBusesReporte.isSelected()){
            //reporte.crearReporteListadoBuses();
        }else if(listadoRutasReporte.isSelected()){
            //reporte.crearReporteListadoRutas();
        }else if(listadoSolicitudesReporte.isSelected()){
            //reporte.crearReporteListadoSolicitudes(dia_s, mes_s, year_s);
        }else if(quejasReporte.isSelected()){
            //reporte.crearReporteQuejas();
        }else{
            
        }
    }//GEN-LAST:event_aceptarSeleccionReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCrearUsuario;
    private javax.swing.JButton aceptarSeleccionReporte;
    private javax.swing.JLabel banner;
    private javax.swing.JComboBox cargoCrearEmpleado;
    private javax.swing.JTextField cedulaCrearEmpleado;
    private javax.swing.JComboBox dia;
    private javax.swing.JButton empleadosBoton;
    private javax.swing.JRadioButton ganaciaVentasReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton listadoBusesReporte;
    private javax.swing.JRadioButton listadoRutasReporte;
    private javax.swing.JRadioButton listadoSolicitudesReporte;
    private javax.swing.JComboBox mes;
    private javax.swing.JTextField nombreCrearEmpleado;
    private javax.swing.JPanel panelAgregarUsuario;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInicialSlogan;
    private javax.swing.JPanel panelSeleccionReporte;
    private javax.swing.JRadioButton pasajeroSistemaReporte;
    private javax.swing.JRadioButton pasajerosMovilizadosReporte;
    private javax.swing.JTextField passwordCrearEmpleado;
    private javax.swing.JRadioButton quejasReporte;
    private javax.swing.JButton reportesBoton;
    private javax.swing.JLabel slogan;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
