/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Estaciones.DAOEstacion;
import Pasajeros.DAOPasajero;
import Rutas.DAORuta;
import Solicitudes.DAOSolicitud;
import Solicitudes.Solicitud;
import Tarjetas.DAOTarjeta;
import Tarjetas.Tarjeta;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Suaza
 */
public class framePasajero extends javax.swing.JFrame {

    /**
     * Creates new form framePasajero
     */
    
    CardLayout clPasajero;
    
    public framePasajero() {
        initComponents();
        
        //Adicion de los paaneles al cardLayout
        panelContenedor.setLayout(new CardLayout());
        
        panelContenedor.add(panelInicialSlogan, "Inicio");
        panelContenedor.add(consultarRutaPanel, "Ruta");
        panelContenedor.add(consultaSaldoPanel, "Saldo");
        panelContenedor.add(abordarBusPanel, "Abordar");
        panelContenedor.add(consultarSolicitudPanel, "Solicitud");
        
        clPasajero = (CardLayout)panelContenedor.getLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarRutaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estacionActual = new javax.swing.JComboBox();
        estacionDestino = new javax.swing.JComboBox();
        buscarConsultarRutaBoton = new javax.swing.JButton();
        mapaConsultarRuta = new javax.swing.JLabel();
        abordarBusPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pinTarjetaAbordar = new javax.swing.JTextField();
        rutaAbordar = new javax.swing.JComboBox();
        abordarRuta = new javax.swing.JButton();
        consultarSolicitudPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        codigoConsultarSolicitud = new javax.swing.JTextField();
        buscarCodigoConsultarSolicitud = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreSolicitud = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        respuestaSolicitud = new javax.swing.JTextArea();
        estacionSolicitud = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        motivoSolicitud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionSolicitud = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        estadoSolicitud = new javax.swing.JLabel();
        aceptarSolicitudBoton = new javax.swing.JButton();
        panelInicialSlogan = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        consultaSaldoPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        codigoConsultar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pasajesActualesConsultar = new javax.swing.JLabel();
        aceptarConsultaSaldo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        buscarCodigoConsultarSaldo = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        consultarSaldo = new javax.swing.JLabel();
        consultarRuta = new javax.swing.JLabel();
        abordarBus = new javax.swing.JLabel();
        consultarSolicitud = new javax.swing.JLabel();
        consultarSaldoBoton = new javax.swing.JButton();
        consultarRutaBoton = new javax.swing.JButton();
        abordarBusBoton = new javax.swing.JButton();
        consultarSolicitudBoton = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();

        consultarRutaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Estación actual:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Estación destino:");

        estacionActual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione una estación --" }));

        estacionDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione una estación --" }));

        buscarConsultarRutaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/buscar.png"))); // NOI18N
        buscarConsultarRutaBoton.setBorder(null);
        buscarConsultarRutaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarConsultarRutaBotonActionPerformed(evt);
            }
        });

        mapaConsultarRuta.setText("IMAGEN MAPA");

        javax.swing.GroupLayout consultarRutaPanelLayout = new javax.swing.GroupLayout(consultarRutaPanel);
        consultarRutaPanel.setLayout(consultarRutaPanelLayout);
        consultarRutaPanelLayout.setHorizontalGroup(
            consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarRutaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultarRutaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buscarConsultarRutaBoton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultarRutaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(estacionDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultarRutaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mapaConsultarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        consultarRutaPanelLayout.setVerticalGroup(
            consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarRutaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarRutaPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(mapaConsultarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(consultarRutaPanelLayout.createSequentialGroup()
                        .addGroup(consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(estacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(consultarRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(estacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buscarConsultarRutaBoton)
                        .addGap(0, 364, Short.MAX_VALUE)))
                .addContainerGap())
        );

        abordarBusPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Pin:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ruta:");

        rutaAbordar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione una ruta --" }));

        abordarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/abordarBus.png"))); // NOI18N
        abordarRuta.setBorder(null);
        abordarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abordarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abordarBusPanelLayout = new javax.swing.GroupLayout(abordarBusPanel);
        abordarBusPanel.setLayout(abordarBusPanelLayout);
        abordarBusPanelLayout.setHorizontalGroup(
            abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abordarBusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abordarRuta)
                    .addGroup(abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(abordarBusPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(30, 30, 30)
                            .addComponent(pinTarjetaAbordar))
                        .addGroup(abordarBusPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(rutaAbordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        abordarBusPanelLayout.setVerticalGroup(
            abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abordarBusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pinTarjetaAbordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abordarBusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rutaAbordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(abordarRuta)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        consultarSolicitudPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Código del tiquete:");

        buscarCodigoConsultarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N
        buscarCodigoConsultarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarCodigoConsultarSolicitudMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Descripción:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Motivo:");

        nombreSolicitud.setText("nombre");

        respuestaSolicitud.setColumns(20);
        respuestaSolicitud.setRows(5);
        jScrollPane2.setViewportView(respuestaSolicitud);

        estacionSolicitud.setText("estacion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre del pasajero:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Respuesta:");

        motivoSolicitud.setText("motivo");

        descripcionSolicitud.setEditable(false);
        descripcionSolicitud.setColumns(20);
        descripcionSolicitud.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descripcionSolicitud.setRows(5);
        jScrollPane1.setViewportView(descripcionSolicitud);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estación:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Estado:");

        estadoSolicitud.setText("estado");

        aceptarSolicitudBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarSolicitudBoton.setBorder(null);
        aceptarSolicitudBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarSolicitudBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarSolicitudPanelLayout = new javax.swing.GroupLayout(consultarSolicitudPanel);
        consultarSolicitudPanel.setLayout(consultarSolicitudPanelLayout);
        consultarSolicitudPanelLayout.setHorizontalGroup(
            consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aceptarSolicitudBoton)
                    .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                        .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                                .addComponent(codigoConsultarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarCodigoConsultarSolicitud))
                            .addComponent(estacionSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(estadoSolicitud)
                                .addComponent(motivoSolicitud))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        consultarSolicitudPanelLayout.setVerticalGroup(
            consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(codigoConsultarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCodigoConsultarSolicitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreSolicitud))
                .addGap(18, 18, 18)
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estacionSolicitud))
                .addGap(18, 18, 18)
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(motivoSolicitud))
                .addGap(18, 18, 18)
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(estadoSolicitud))
                .addGap(18, 18, 18)
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarSolicitudPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(126, 126, 126))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(consultarSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7))
                    .addGroup(consultarSolicitudPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(aceptarSolicitudBoton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelInicialSlogan.setBackground(new java.awt.Color(255, 255, 255));

        slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/slogan.png"))); // NOI18N

        javax.swing.GroupLayout panelInicialSloganLayout = new javax.swing.GroupLayout(panelInicialSlogan);
        panelInicialSlogan.setLayout(panelInicialSloganLayout);
        panelInicialSloganLayout.setHorizontalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(slogan)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelInicialSloganLayout.setVerticalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(slogan)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        consultaSaldoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Código de la tarjeta:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Cantidad actual:");

        pasajesActualesConsultar.setText("0");

        aceptarConsultaSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarConsultaSaldo.setBorder(null);
        aceptarConsultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarConsultaSaldoActionPerformed(evt);
            }
        });

        jLabel6.setText("tiquetes");

        buscarCodigoConsultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/search.png"))); // NOI18N
        buscarCodigoConsultarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarCodigoConsultarSaldoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout consultaSaldoPanelLayout = new javax.swing.GroupLayout(consultaSaldoPanel);
        consultaSaldoPanel.setLayout(consultaSaldoPanelLayout);
        consultaSaldoPanelLayout.setHorizontalGroup(
            consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                        .addComponent(pasajesActualesConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                        .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptarConsultaSaldo)
                            .addComponent(codigoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarCodigoConsultarSaldo)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        consultaSaldoPanelLayout.setVerticalGroup(
            consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaSaldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(codigoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarCodigoConsultarSaldo))
                .addGap(18, 18, 18)
                .addGroup(consultaSaldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pasajesActualesConsultar)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptarConsultaSaldo)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        consultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/dollar-symbol-2.png"))); // NOI18N

        consultarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/maps-and-flags-4.png"))); // NOI18N

        abordarBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/bus.png"))); // NOI18N

        consultarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/file-2.png"))); // NOI18N

        consultarSaldoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/consultarSaldo.png"))); // NOI18N
        consultarSaldoBoton.setBorder(null);
        consultarSaldoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarSaldoBotonActionPerformed(evt);
            }
        });

        consultarRutaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/consultarRuta.png"))); // NOI18N
        consultarRutaBoton.setBorder(null);
        consultarRutaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarRutaBotonActionPerformed(evt);
            }
        });

        abordarBusBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/abordarBus.png"))); // NOI18N
        abordarBusBoton.setBorder(null);
        abordarBusBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abordarBusBotonActionPerformed(evt);
            }
        });

        consultarSolicitudBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/consuultarSolicitud.png"))); // NOI18N
        consultarSolicitudBoton.setBorder(null);
        consultarSolicitudBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarSolicitudBotonActionPerformed(evt);
            }
        });

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banner.png"))); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(consultarRuta)
                        .addGap(18, 18, 18)
                        .addComponent(consultarRutaBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(consultarSaldo)
                        .addGap(18, 18, 18)
                        .addComponent(consultarSaldoBoton))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abordarBus)
                            .addComponent(consultarSolicitud))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abordarBusBoton)
                            .addComponent(consultarSolicitudBoton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(17, 17, 17)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarSaldo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarSaldoBoton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarRuta)
                            .addComponent(consultarRutaBoton))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(abordarBus)
                            .addComponent(abordarBusBoton))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarSolicitud)
                            .addComponent(consultarSolicitudBoton)))
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarSaldoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarSaldoBotonActionPerformed
        panelContenedor.setVisible(true);
        clPasajero.show(panelContenedor, "Saldo");
    }//GEN-LAST:event_consultarSaldoBotonActionPerformed

    private void consultarRutaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarRutaBotonActionPerformed
        panelContenedor.setVisible(true);
        clPasajero.show(panelContenedor, "Ruta");
        new DAOEstacion().agregarEstaciones(estacionActual);
        new DAOEstacion().agregarEstaciones(estacionDestino);
    }//GEN-LAST:event_consultarRutaBotonActionPerformed

    private void abordarBusBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abordarBusBotonActionPerformed
        panelContenedor.setVisible(true);
        new DAORuta().agregarRutas(rutaAbordar);
        clPasajero.show(panelContenedor, "Abordar");
    }//GEN-LAST:event_abordarBusBotonActionPerformed

    private void consultarSolicitudBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarSolicitudBotonActionPerformed
        panelContenedor.setVisible(true);
        clPasajero.show(panelContenedor, "Solicitud");
    }//GEN-LAST:event_consultarSolicitudBotonActionPerformed

    private void aceptarConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarConsultaSaldoActionPerformed
        clPasajero.show(panelContenedor, "Inicio");
    }//GEN-LAST:event_aceptarConsultaSaldoActionPerformed

    private void buscarConsultarRutaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarConsultarRutaBotonActionPerformed
        String estActual = estacionActual.getSelectedItem().toString();
        String estDestino = estacionDestino.getSelectedItem().toString();
        String rutas = new DAORuta().consultarRuta(estActual, estDestino);
        System.out.println(rutas);
    }//GEN-LAST:event_buscarConsultarRutaBotonActionPerformed

    private void abordarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abordarRutaActionPerformed
        // TODO add your handling code here:
        int pin = Integer.parseInt(pinTarjetaAbordar.getText());
        Tarjeta tarjeta = new DAOTarjeta().consultarTarjeta(pinTarjetaAbordar.getText());
        String estacion_nombre = rutaAbordar.getSelectedItem().toString();
        int ruta = new DAORuta().consultarRuta(estacion_nombre);
        int add = new DAOTarjeta().abordarBus(pin, ruta);
        if(add > 0){
            JOptionPane.showMessageDialog(null, "bus abordado");
            new DAOTarjeta().modificarTarjeta(tarjeta);
        }else{
            JOptionPane.showMessageDialog(null, "Error, pase la tarjeta otra vez");
        }
    }//GEN-LAST:event_abordarRutaActionPerformed

    private void aceptarSolicitudBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarSolicitudBotonActionPerformed
        // TODO add your handling code here:
        clPasajero.show(panelContenedor, "Inicio");
    }//GEN-LAST:event_aceptarSolicitudBotonActionPerformed

    private void buscarCodigoConsultarSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarCodigoConsultarSolicitudMouseClicked
        // TODO add your handling code here:
        String tiquete = codigoConsultarSolicitud.getText();
        Solicitud solicitud = new DAOSolicitud().obtenerSolicitud(tiquete);
        
        if(solicitud.isEstadSolicitud()){
            estadoSolicitud.setText("Activa");
        }else{
            estadoSolicitud.setText("Inactiva");
        }
        motivoSolicitud.setText(solicitud.getMotivoSolicitud());
        descripcionSolicitud.setText(solicitud.getDescripcionSolicitud());
        respuestaSolicitud.setText(solicitud.getRespuesta());
        nombreSolicitud.setText(new DAOPasajero().obtenerNombrePasajero(tiquete));
        estacionSolicitud.setText(new DAOEstacion().consultarEstacionSolicitud(tiquete));
    }//GEN-LAST:event_buscarCodigoConsultarSolicitudMouseClicked

    private void buscarCodigoConsultarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarCodigoConsultarSaldoMouseClicked
        String codigo_tarjeta = codigoConsultar.getText();
        int numeroPasajes = new DAOTarjeta().consultarTarjeta(codigo_tarjeta).getNumero_pasajes();
        pasajesActualesConsultar.setText(Integer.toString(numeroPasajes));
        
    }//GEN-LAST:event_buscarCodigoConsultarSaldoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePasajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abordarBus;
    private javax.swing.JButton abordarBusBoton;
    private javax.swing.JPanel abordarBusPanel;
    private javax.swing.JButton abordarRuta;
    private javax.swing.JButton aceptarConsultaSaldo;
    private javax.swing.JButton aceptarSolicitudBoton;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel buscarCodigoConsultarSaldo;
    private javax.swing.JLabel buscarCodigoConsultarSolicitud;
    private javax.swing.JButton buscarConsultarRutaBoton;
    private javax.swing.JTextField codigoConsultar;
    private javax.swing.JTextField codigoConsultarSolicitud;
    private javax.swing.JPanel consultaSaldoPanel;
    private javax.swing.JLabel consultarRuta;
    private javax.swing.JButton consultarRutaBoton;
    private javax.swing.JPanel consultarRutaPanel;
    private javax.swing.JLabel consultarSaldo;
    private javax.swing.JButton consultarSaldoBoton;
    private javax.swing.JLabel consultarSolicitud;
    private javax.swing.JButton consultarSolicitudBoton;
    private javax.swing.JPanel consultarSolicitudPanel;
    private javax.swing.JTextArea descripcionSolicitud;
    private javax.swing.JComboBox estacionActual;
    private javax.swing.JComboBox estacionDestino;
    private javax.swing.JLabel estacionSolicitud;
    private javax.swing.JLabel estadoSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mapaConsultarRuta;
    private javax.swing.JLabel motivoSolicitud;
    private javax.swing.JLabel nombreSolicitud;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInicialSlogan;
    private javax.swing.JLabel pasajesActualesConsultar;
    private javax.swing.JTextField pinTarjetaAbordar;
    private javax.swing.JTextArea respuestaSolicitud;
    private javax.swing.JComboBox rutaAbordar;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
