/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Juan Suaza
 */
public class frameDirectorEstacion extends javax.swing.JFrame {

    /**
     * Creates new form frameDirectorEstacion
     */
    public frameDirectorEstacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameSolucionar = new javax.swing.JFrame();
        solicitudSolucion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombrePasajeroSolucionar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estacionSolucionar = new javax.swing.JLabel();
        motivoSolucionar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionSolucionar = new javax.swing.JTextArea();
        resolverSolucionarBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        respuestaSolucionar = new javax.swing.JTextArea();
        frameModificarUsuario = new javax.swing.JFrame();
        modificarUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaModificarUsuario = new javax.swing.JTextField();
        nombreModificarUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aceptarModificarUsuario = new javax.swing.JButton();
        panelInicialSlogan = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        auxiliaresPanel = new javax.swing.JPanel();
        tablaAuxiliaresPanel = new javax.swing.JPanel();
        modificarUsuarioBoton = new javax.swing.JButton();
        resolverSolicitudPanel = new javax.swing.JPanel();
        tablaSolicitudesPanel = new javax.swing.JPanel();
        resolverSolicitud = new javax.swing.JButton();
        panelFondo = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        auxiliaresBoton = new javax.swing.JButton();
        resolverSolicitudesBoton = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        solicitudSolucion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre del pasajero:");

        nombrePasajeroSolucionar.setText("nombre");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Motivo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Descripción:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estación:");

        estacionSolucionar.setText("estacion");

        motivoSolucionar.setText("motivo");

        descripcionSolucionar.setEditable(false);
        descripcionSolucionar.setColumns(20);
        descripcionSolucionar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        descripcionSolucionar.setRows(5);
        jScrollPane1.setViewportView(descripcionSolucionar);

        resolverSolucionarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/resolver.png"))); // NOI18N
        resolverSolucionarBoton.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Respuesta:");

        respuestaSolucionar.setColumns(20);
        respuestaSolucionar.setRows(5);
        jScrollPane2.setViewportView(respuestaSolucionar);

        javax.swing.GroupLayout solicitudSolucionLayout = new javax.swing.GroupLayout(solicitudSolucion);
        solicitudSolucion.setLayout(solicitudSolucionLayout);
        solicitudSolucionLayout.setHorizontalGroup(
            solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resolverSolucionarBoton)
                    .addGroup(solicitudSolucionLayout.createSequentialGroup()
                        .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(motivoSolucionar)
                            .addComponent(nombrePasajeroSolucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estacionSolucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        solicitudSolucionLayout.setVerticalGroup(
            solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudSolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombrePasajeroSolucionar))
                .addGap(18, 18, 18)
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estacionSolucionar))
                .addGap(18, 18, 18)
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(motivoSolucionar))
                .addGap(18, 18, 18)
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(solicitudSolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solicitudSolucionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7))
                    .addGroup(solicitudSolucionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(resolverSolucionarBoton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameSolucionarLayout = new javax.swing.GroupLayout(frameSolucionar.getContentPane());
        frameSolucionar.getContentPane().setLayout(frameSolucionarLayout);
        frameSolucionarLayout.setHorizontalGroup(
            frameSolucionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(frameSolucionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(solicitudSolucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameSolucionarLayout.setVerticalGroup(
            frameSolucionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(frameSolucionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameSolucionarLayout.createSequentialGroup()
                    .addComponent(solicitudSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        modificarUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Cédula:");

        jLabel4.setText("Nombre:");

        cedulaModificarUsuario.setEditable(false);
        cedulaModificarUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/compose.png"))); // NOI18N

        aceptarModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/aceptar.png"))); // NOI18N
        aceptarModificarUsuario.setBorder(null);

        javax.swing.GroupLayout modificarUsuarioLayout = new javax.swing.GroupLayout(modificarUsuario);
        modificarUsuario.setLayout(modificarUsuarioLayout);
        modificarUsuarioLayout.setHorizontalGroup(
            modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarUsuarioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarUsuarioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6))
                    .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(aceptarModificarUsuario)
                        .addGroup(modificarUsuarioLayout.createSequentialGroup()
                            .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(modificarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(14, 14, 14)))
                            .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cedulaModificarUsuario)
                                .addComponent(nombreModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        modificarUsuarioLayout.setVerticalGroup(
            modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarUsuarioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cedulaModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(modificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptarModificarUsuario)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameModificarUsuarioLayout = new javax.swing.GroupLayout(frameModificarUsuario.getContentPane());
        frameModificarUsuario.getContentPane().setLayout(frameModificarUsuarioLayout);
        frameModificarUsuarioLayout.setHorizontalGroup(
            frameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(frameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameModificarUsuarioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        frameModificarUsuarioLayout.setVerticalGroup(
            frameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(frameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameModificarUsuarioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelInicialSlogan.setBackground(new java.awt.Color(255, 255, 255));

        slogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/slogan.png"))); // NOI18N

        javax.swing.GroupLayout panelInicialSloganLayout = new javax.swing.GroupLayout(panelInicialSlogan);
        panelInicialSlogan.setLayout(panelInicialSloganLayout);
        panelInicialSloganLayout.setHorizontalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialSloganLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(slogan)
                .addGap(39, 39, 39))
        );
        panelInicialSloganLayout.setVerticalGroup(
            panelInicialSloganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialSloganLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(slogan)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        auxiliaresPanel.setBackground(new java.awt.Color(255, 255, 255));

        tablaAuxiliaresPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tablaAuxiliaresPanelLayout = new javax.swing.GroupLayout(tablaAuxiliaresPanel);
        tablaAuxiliaresPanel.setLayout(tablaAuxiliaresPanelLayout);
        tablaAuxiliaresPanelLayout.setHorizontalGroup(
            tablaAuxiliaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablaAuxiliaresPanelLayout.setVerticalGroup(
            tablaAuxiliaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        modificarUsuarioBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/modificar.png"))); // NOI18N
        modificarUsuarioBoton.setBorder(null);

        javax.swing.GroupLayout auxiliaresPanelLayout = new javax.swing.GroupLayout(auxiliaresPanel);
        auxiliaresPanel.setLayout(auxiliaresPanelLayout);
        auxiliaresPanelLayout.setHorizontalGroup(
            auxiliaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaAuxiliaresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auxiliaresPanelLayout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addComponent(modificarUsuarioBoton)
                .addContainerGap())
        );
        auxiliaresPanelLayout.setVerticalGroup(
            auxiliaresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auxiliaresPanelLayout.createSequentialGroup()
                .addComponent(tablaAuxiliaresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarUsuarioBoton)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        resolverSolicitudPanel.setBackground(new java.awt.Color(255, 255, 255));

        tablaSolicitudesPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tablaSolicitudesPanelLayout = new javax.swing.GroupLayout(tablaSolicitudesPanel);
        tablaSolicitudesPanel.setLayout(tablaSolicitudesPanelLayout);
        tablaSolicitudesPanelLayout.setHorizontalGroup(
            tablaSolicitudesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        tablaSolicitudesPanelLayout.setVerticalGroup(
            tablaSolicitudesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        resolverSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/resolver.png"))); // NOI18N
        resolverSolicitud.setBorder(null);

        javax.swing.GroupLayout resolverSolicitudPanelLayout = new javax.swing.GroupLayout(resolverSolicitudPanel);
        resolverSolicitudPanel.setLayout(resolverSolicitudPanelLayout);
        resolverSolicitudPanelLayout.setHorizontalGroup(
            resolverSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaSolicitudesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resolverSolicitudPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resolverSolicitud)
                .addContainerGap())
        );
        resolverSolicitudPanelLayout.setVerticalGroup(
            resolverSolicitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resolverSolicitudPanelLayout.createSequentialGroup()
                .addComponent(tablaSolicitudesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resolverSolicitud)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/banner.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/users-1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/archive-3.png"))); // NOI18N

        auxiliaresBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/auxiliares.png"))); // NOI18N
        auxiliaresBoton.setBorder(null);

        resolverSolicitudesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/Botones/resolverSolicitudes.png"))); // NOI18N
        resolverSolicitudesBoton.setBorder(null);

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(auxiliaresBoton))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(resolverSolicitudesBoton)))
                        .addGap(34, 34, 34)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(auxiliaresBoton))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(resolverSolicitudesBoton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDirectorEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDirectorEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDirectorEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDirectorEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDirectorEstacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarModificarUsuario;
    private javax.swing.JButton auxiliaresBoton;
    private javax.swing.JPanel auxiliaresPanel;
    private javax.swing.JLabel banner;
    private javax.swing.JTextField cedulaModificarUsuario;
    private javax.swing.JTextArea descripcionSolucionar;
    private javax.swing.JLabel estacionSolucionar;
    private javax.swing.JFrame frameModificarUsuario;
    private javax.swing.JFrame frameSolucionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel modificarUsuario;
    private javax.swing.JButton modificarUsuarioBoton;
    private javax.swing.JLabel motivoSolucionar;
    private javax.swing.JTextField nombreModificarUsuario;
    private javax.swing.JLabel nombrePasajeroSolucionar;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInicialSlogan;
    private javax.swing.JButton resolverSolicitud;
    private javax.swing.JPanel resolverSolicitudPanel;
    private javax.swing.JButton resolverSolicitudesBoton;
    private javax.swing.JButton resolverSolucionarBoton;
    private javax.swing.JTextArea respuestaSolucionar;
    private javax.swing.JLabel slogan;
    private javax.swing.JPanel solicitudSolucion;
    private javax.swing.JPanel tablaAuxiliaresPanel;
    private javax.swing.JPanel tablaSolicitudesPanel;
    // End of variables declaration//GEN-END:variables
}
